/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    alias(libs.plugins.spotless)
    alias(libs.plugins.download)
    alias(libs.plugins.shadow)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val downloadWebdsl by tasks.registering(de.undercouch.gradle.tasks.download.Download::class) {
  src("https://update.webdsl.org/compiler/webdsl.zip")
  dest(layout.buildDirectory.file("webdsl.zip"))
}

val webdslJarFiles = listOf("strategoxt.jar", "webdsl.jar").map { "webdsl/bin/$it" }
val webdslResources = listOf("webdsl/share/webdsl/template-webdsl/built-in.app")

val downloadAndExtractWebdsl = tasks.register<Copy>("downloadAndExtractWebdsl") {
  if (!downloadWebdsl.get().dest.exists()) {
    dependsOn(downloadWebdsl)
  }

  from(zipTree(downloadWebdsl.get().dest))
  into(layout.buildDirectory)
  include(*webdslJarFiles.toTypedArray(), *webdslResources.toTypedArray())
}

sourceSets["main"].resources.srcDir(layout.buildDirectory.file("webdsl/share"))

tasks.register<Delete>("cleanWebdsl") {
  delete(layout.buildDirectory.dir("webdsl"), downloadWebdsl.get().dest)
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.lsp4j)
    implementation(libs.lsp4j.jsonrpc)

    implementation(files(
      *webdslJarFiles.map { layout.buildDirectory.file(it) }.toTypedArray()
    ))
}

tasks.named("compileJava") {
  dependsOn(downloadAndExtractWebdsl)
}

tasks.named("compileKotlin") {
  dependsOn(downloadAndExtractWebdsl)
}

tasks.named("processResources") {
  dependsOn(downloadAndExtractWebdsl)
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
  archiveBaseName = "webdsl-lsp"
  archiveClassifier = ""
  archiveVersion = "1.0.0"
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.webdsl.lsp.AppKt"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

spotless {
  kotlin {
    ktlint("1.0.0")
      .setEditorConfigPath("$projectDir/config/.editorconfig")
      .editorConfigOverride(
        mapOf(
          "indent_size" to 2,
          "ktlint_code_style" to "intellij_idea",
        )
      )
      .customRuleSets(
        listOf(
          "io.nlopez.compose.rules:ktlint:0.4.25"
        )
      )
  }
}
